### ISSUE TITLE
可以增加几种群组么，如果国内的有竞争关系，可以用gitter嘛？

### ISSUE THREAD

**Issue by sunfuze** [aliyun-node/agentx#21]
mac下的泡泡没有加群的功能，更不用说linux。

**Comment by yjhjstz** [comment]
gitter 普通版 LIMITED TO 25 USERS PER PRIVATE ROOM， 这个也是鸡肋吧。

**Comment by fengmk2** [comment]
dingding啊

**Comment by sunfuze** [comment]
@yjhjstz 这个需要private room么，public不就好了
