### ISSUE TITLE
alinode 是开源的吗？

### ISSUE THREAD

**Issue by Jianru-Lin** [aliyun-node/agentx#38]
是否已经开源，或者有这方面的计划？

谢谢。

**Comment by JacksonTian** [comment]
需要运行在用户机器上的软件，我们除了 alinode runtime binary 不开源外，其余都会开源。

尽管不开源，但这个服务是可以免费使用部分功能的。

**Comment by Jianru-Lin** [comment]
好的明白了，感谢回复。
